# frozen_string_literal: true

gem "jekyll-remote-theme"
source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem "jekyll"
gem 'jekyll-feed'
gem 'jekyll-readme-index'
gem 'jemoji'
gem 'webrick'
gem "kramdown-parser-gfm"

# gem "rails"